cambio en entrypoint

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -1,6 +1,14 @@
 #!/bin/bash
 set -e
 
+# Exportar variables para asegurar el PATH
+export BUNDLE_PATH="/usr/local/bundle"
+export PATH="$BUNDLE_PATH/bin:$PATH"
+
+echo "PATH is: $PATH"
+which bundle || echo "bundle not found"
+which rails || echo "rails not found"
+
 echo "Ejecutando migraciones de base de datos..."
 bundle exec rails db:migrate
 
